### ISSUE TITLE
PastPlace Logo

### ISSUE THREAD

**Issue by klokan** [klokantech/pastplace#1]
Create a logo for the PastPlace project.

**Comment by klokan** [comment]
first ideas:
![2b57a8ae-52ca-11e4-8bef-3e0d5c584c47](https://cloud.githubusercontent.com/assets/59284/4612961/ee36fdc0-52cf-11e4-8192-b2379061c987.png)

**Comment by klokan** [comment]
Done at:
https://www.pixelapse.com/klokantech/projects/pastplace/logo/

**Comment by klokan** [comment]
The logo for mobile needs to be updated - with gradients.

**Comment by klokan** [comment]
@TomasKlanica could you please prepare a large 1024x1024 pixel image for the main mobile app logo?

It should have similar background color (old paper color) as OldMapsOnline and in foreground the gradiented PastPlace logo as on the frontpage. No text.

Thanks!

**Comment by TomasKlanica** [comment]
I placed the logo 1024x1024 on the folder Pixelapse 1024x1024 Logo.

**Comment by klokan** [comment]
Please put it to https://www.pixelapse.com/klokantech/projects/pastplace/logo/ where it belongs.

I see two problems (i looked only at PNG variant):
- it is not yet centered and large to fill the 1024x1024 space as in here:
  ![logo](https://cloud.githubusercontent.com/assets/59284/7953531/d11cdb40-09ce-11e5-8870-def15126da4d.png)
- there is the ugly white one-pixel line around the marker

Please fix it and post here link to pixelapse afterwards.

This version of logo is to be used as favicon and mobile app icon, as well as buddy icon for facebook / twitter etc.

**Comment by TomasKlanica** [comment]
Done

**Comment by klokan** [comment]
I don't see it at:
https://www.pixelapse.com/klokantech/projects/pastplace/logo/

**Comment by TomasKlanica** [comment]
I do not know where the problem is. I'll try it again.

**Comment by klokan** [comment]
https://www.pixelapse.com/klokantech/projects/pastplace/logo/1024x1024-logo.png

**Comment by klokan** [comment]
Thanks!
