### ISSUE TITLE
Favicon + touch icon

### ISSUE THREAD

**Issue by klokan** [klokantech/pastplace#10]
Generate from this image:
https://www.pixelapse.com/klokantech/projects/pastplace/logo/1024x1024-logo.png

And apply on all pages.

Change the background color on the icon to be the same as in the header in HTML.
Paste the updated PNG here, please.

**Comment by daliborjanak** [comment]
![1024x1024-logo](https://cloud.githubusercontent.com/assets/1891090/8144534/646d8fea-11e3-11e5-97a4-82b6e1436956.png)
